### ISSUE TITLE
Proposal to delete orphaned [p key_commands]

### ISSUE THREAD

**Issue by delucis** [mus264/music-264-modular#3]
The key commands subpatcher (contained in the [control] subpatcher) is currently orphaned. I would propose removing it until such a time as we decide to implement keyboard shortcuts. Then we can create a custom system tailored to our needs.

![Screen shot of the key commands subpatcher](https://cloud.githubusercontent.com/assets/357379/6386311/d5a48928-bd44-11e4-8545-3c0dcddc6877.png)

**Comment by hanstutschku** [comment]
We will need it soon. Leave it in there for now
